name: Deploy

on:
  push:
    branches:
      - main  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.virtualekubdash.com                     # FTP server address
          username: public_html@virtualekubdash.com           # Full FTP username
          password: ${{ secrets.FTP_PASSWORD }}               # Reference the secret for the password
          protocol: ftp                                       # Use 'ftp' or 'ftps' as needed
          local-dir: ./                                       # Directory containing files to deploy
         