name: Deploy

on:
  push:
    branches:
      - main  # or the branch you want to trigger the workflow on

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Run deployment script
        run: echo "Deploying..."