name: Deploy

on:
  push:
    branches:
      - main  # Specify the target branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_SERVER }}          # FTP server address
          username: ${{ secrets.FTP_USERNAME }}      # FTP username
          password: ${{ secrets.FTP_PASSWORD }}      # FTP password
          local-dir: './'                               # Local directory to deploy
          protocol: ftp
          server-dir: /home/virtualekubdash.com/test/ # Remote directory on the server
          