name: Deploye
on:
  push:
    branches:
main
jobs:
  deploy:
    name:  Deploy website every commit
    runs-on: ubuntu-latest
    steps:
name:  Get latest code
        uses: actions/checkout@v2

name: FTP-Deploy-Action
        with:
          server: ftp.virtualekubdash.com
          username: test@test.virtualekubdash.com
          password:'(7^xbOazFA=D'
          protocol: ftps
          port: 21 
          local-dir: './'